version: '2.1'
services:
  squidex_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  squidex_eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    restart: always
    environment:
      - "EVENTSTORE_RUN_PROJECTIONS=All"