version: '2.1'
services:
  squidex_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  squidex_redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    restart: always

  squidex_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  squidex_eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    restart: always
    environment:
      - "EVENTSTORE_RUN_PROJECTIONS=All"